language: node_js
node_js:
- '8'
- '10'
- 'stable'
cache:
  directories:
  - node_modules
  - "$(npm config get prefix)/node_modules"
before_install: npm install
script: npm run build && npm run test-ci
after_success: npm install coveralls && cat ./coverage/lcov.info | coveralls